/* This file was generated by bin2c. */
#ifndef MERGED_BIN_H
#define MERGED_BIN_H

#define MERGED_BIN_SIZE ((unsigned long)5981346)

typedef enum
{
    IMG_DEMO_ARGB8565_INDEXQOI_ID = 0,
    IMG_DEMO_RGB565_ID = 1,
    IMG_DEMO_RGB565_INDEXQOI_ID = 2,
    IMG_DEMO_RGB565_INDEXQOI2_ID = 3,
    MSYH_16_4BBP_ASCII_MENU_MIX_ID = 4,
    MSYH_24_2BBP_ASCII_MENU_MIX_ID = 5,
    bin_COUNT = 6
} bin_id_t;

#define IMG_DEMO_ARGB8565_INDEXQOI_SIZE ((unsigned long)6603)
#define IMG_DEMO_RGB565_SIZE ((unsigned long)16390)
#define IMG_DEMO_RGB565_INDEXQOI_SIZE ((unsigned long)5159)
#define IMG_DEMO_RGB565_INDEXQOI2_SIZE ((unsigned long)10666)
#define MSYH_16_4BBP_ASCII_MENU_MIX_SIZE ((unsigned long)2801882)
#define MSYH_24_2BBP_ASCII_MENU_MIX_SIZE ((unsigned long)3140646)

static const unsigned long bin_addr_table[bin_COUNT] =
{
    0, //IMG_DEMO_ARGB8565_INDEXQOI
    6603, //IMG_DEMO_RGB565
    22993, //IMG_DEMO_RGB565_INDEXQOI
    28152, //IMG_DEMO_RGB565_INDEXQOI2
    38818, //MSYH_16_4BBP_ASCII_MENU_MIX
    2840700, //MSYH_24_2BBP_ASCII_MENU_MIX
};

#define IMG_DEMO_ARGB8565_INDEXQOI_ADDR ((unsigned long)0)
#define IMG_DEMO_RGB565_ADDR ((unsigned long)6603)
#define IMG_DEMO_RGB565_INDEXQOI_ADDR ((unsigned long)22993)
#define IMG_DEMO_RGB565_INDEXQOI2_ADDR ((unsigned long)28152)
#define MSYH_16_4BBP_ASCII_MENU_MIX_ADDR ((unsigned long)38818)
#define MSYH_24_2BBP_ASCII_MENU_MIX_ADDR ((unsigned long)2840700)

#endif
