/* auto-generated by tool/pinyin2c/gen_pinyin_table.py -- DO NOT EDIT
 * preset      : l1l2
 * syllables   : 400
 * L1 cands    : 3822
 * L2 cands    : 3008
 * ROM approx  : 18460 bytes (400 * 12 + 6830 * 2)
 * 数据来源：GB2312 字集 + pypinyin 注音（白名单过滤），详见 tool/pinyin2c/README.md
 */
#ifndef __WE_PINYIN_TABLE_H
#define __WE_PINYIN_TABLE_H

#include <stdint.h>

/* 二级字段编译期开关：0 = 表内含二级字但引擎只遍历一级段（默认），
 * 1 = 编译进二级段遍历支持（运行期再经 we_pinyin_set_l2 开关）。
 * 只想彻底省 ROM 请改用 l1 预设表覆盖本表（见 tool/pinyin2c/README.md）。 */
#ifndef WE_PINYIN_ENABLE_L2
#define WE_PINYIN_ENABLE_L2 0
#endif

#define WE_PINYIN_SYLLABLE_COUNT 400U
#define WE_PINYIN_CAND_COUNT     6830U
#define WE_PINYIN_MAX_LEN        6

/* 排序音节表条目：py 字典序升序；候选段 = we_pinyin_cands[cand_ofs ..)，
 * 段内一级字在前（按常用度排序），二级字接在后。 */
typedef struct
{
    char py[7];      /* 音节字母（NUL 结尾） */
    uint16_t cand_ofs;  /* 候选段在 we_pinyin_cands 中的起始下标 */
    uint8_t l1_cnt;     /* 段内一级字数 */
    uint8_t total_cnt;  /* 段内总字数（一级 + 二级） */
} we_pinyin_syllable_t;

extern const we_pinyin_syllable_t we_pinyin_syllables[WE_PINYIN_SYLLABLE_COUNT];
extern const uint16_t we_pinyin_cands[WE_PINYIN_CAND_COUNT];

#endif /* __WE_PINYIN_TABLE_H */
