/*
 * Generated by font2c.
 * config: gbsn00lp_2_16_4bpp.json
 * symbol: gbsn00lp_2_16_4bpp
 * deploy mode: external
 * source font: gbsn00lp-2.ttf
 * face index: 0
 * font size: 16 px
 * bpp: 4
 * line_height: 16
 * baseline: 15
 * max_box_width: 16
 * max_box_height: 18
 * glyph_count: 20997
 * ranges (normalized):
 *   U+0020( ) - U+007E(~)
 *   U+4E00(一) - U+9FA5(龥)
 * direct chars (input):
 *   (none)
 * direct chars (normalized sparse):
 *   (none)
 * blob_size: 2562276
 * blob_crc32: 0xB75087BC
 * external blob layout: [0]=0x02 [1]=0x00 [2:5]=crc32_be [6:...]=glyph_desc+bitmap
 * user binds blob_addr at runtime through font_external_handle_t.
 */
#include <stddef.h>
#include <stdint.h>
#include "gbsn00lp_2_16_4bpp.h"

static const font_range_t gbsn00lp_2_16_4bpp_ranges[] = {
    { .start = 0x00000020u, .end = 0x0000007Eu },
    { .start = 0x00004E00u, .end = 0x00009FA5u },
};

const font_external_t gbsn00lp_2_16_4bpp = {
    .bpp = 4u,
    .line_height = 16u,
    .baseline = 15u,
    .range_count = 2u,
    .sparse_count = 0u,
    .glyph_count = 20997u,
    .max_box_width = 16u,
    .max_box_height = 18u,
    .ranges = gbsn00lp_2_16_4bpp_ranges,
    .sparse = NULL,
    .blob_size = 2562276u,
    .blob_crc32 = 0xB75087BCu
};
