/*
 * Generated by font2c.
 * config: msyh_16_4bbp_ascii_menu_mix.json
 * symbol: msyh_16_4bbp_ascii_menu_mix
 * deploy mode: external
 * source font: msyh.ttc
 * face index: 0
 * font size: 16 px
 * bpp: 4
 * line_height: 21
 * baseline: 17
 * max_box_width: 17
 * max_box_height: 17
 * glyph_count: 21087
 * ranges (normalized):
 *   U+0020( ) - U+007E(~)
 *   U+4E00(一) - U+9FFF(鿿)
 * direct chars (input):
 *   菜单设置返回确定
 * direct chars (normalized sparse):
 *   (none)
 * blob_size: 2801882
 * blob_crc32: 0x307A67FB
 * external blob layout: [0]=0x02 [1]=0x00 [2:5]=crc32_be [6:...]=glyph_desc+bitmap
 * user binds blob_addr at runtime through font_external_handle_t.
 */
#include <stddef.h>
#include <stdint.h>
#include "msyh_16_4bbp_ascii_menu_mix.h"

static const font_range_t msyh_16_4bbp_ascii_menu_mix_ranges[] = {
    { .start = 0x00000020u, .end = 0x0000007Eu },
    { .start = 0x00004E00u, .end = 0x00009FFFu },
};

const font_external_t msyh_16_4bbp_ascii_menu_mix = {
    .bpp = 4u,
    .line_height = 21u,
    .baseline = 17u,
    .range_count = 2u,
    .sparse_count = 0u,
    .glyph_count = 21087u,
    .max_box_width = 17u,
    .max_box_height = 17u,
    .ranges = msyh_16_4bbp_ascii_menu_mix_ranges,
    .sparse = NULL,
    .blob_size = 2801882u,
    .blob_crc32 = 0x307A67FBu
};
