# update_resources.ps1 — WeGui 资源一键更新
#
# 流程：清 build → [字符集扫描(待 font2c scan 就位)] → font2c 字库
#       → img2bin_pack 图片取模 → 归一化(补 v2 头 + 角色短名)
#       → 生成 out/res_images.c/.h → bin2c 合并 → 尺寸汇总
#
# 产物全部落在 out/，三个构建目标只消费 out/。
$ErrorActionPreference = 'Stop'

# ================= 配置区 =================
# img2bin 六工具是否默认输出 6 字节 v2 信息头
# （2026-07-26 起工具恒定带头；置 $false 可兼容旧版纯 payload 工具）
$IMG2BIN_HAS_HEADER = $true

# 内部 flash 数组清单：这些角色会生成进 out/res_images.c/.h 参与固件编译；
# 未列出的角色只进入外挂合并包。
$INTERNAL_IMAGES = @('demo_sprite', 'demo_qoi', 'demo_overlay', 'demo_alpha')

# 参与取模的图片文件夹（img2bin_pack --folders）
$IMG_FOLDERS = 'input2raw,input2indexqoi,alpha_indexqoi'
# ==========================================

$res    = $PSScriptRoot
$root   = (Resolve-Path (Join-Path $res '..\..')).Path
$pack   = Join-Path $root 'tool\img2c\windows\img2bin_pack.exe'
$bin2c  = Join-Path $root 'tool\bin2c\bin2c.exe'
$font2c = Join-Path $root 'tool\font2c\font2c.exe'

foreach ($t in @($pack, $bin2c, $font2c)) {
    if (-not (Test-Path $t)) { throw "工具缺失: $t" }
}

# ---- 1. 清理中间产物（防止已删除/改名的旧 bin 混入合并包） ----
if (Test-Path (Join-Path $res 'build')) { Remove-Item -Recurse -Force (Join-Path $res 'build') }
New-Item -ItemType Directory -Force (Join-Path $res 'build\img') | Out-Null
New-Item -ItemType Directory -Force (Join-Path $res 'out\font') | Out-Null

# ---- 2. 字符集扫描：源码字符串 -> 回写 CJK 字库配置的 charset.chars ----
Write-Host '==== font2c scan ===='
& $font2c scan --src (Join-Path $root 'Demo') --extra (Join-Path $res 'extra_chars.txt') --json (Join-Path $res 'font_cfgs\demo_cjk_16.json')
if ($LASTEXITCODE -ne 0) { throw "font2c scan 失败 (exit $LASTEXITCODE)" }
& $font2c scan --src (Join-Path $root 'Demo') --extra (Join-Path $res 'extra_chars.txt') --json (Join-Path $res 'font_cfgs\demo_cjk_24.json')
if ($LASTEXITCODE -ne 0) { throw "font2c scan 失败 (exit $LASTEXITCODE)" }

# ---- 3. 字库取模 ----
Write-Host '==== font2c ===='
& $font2c build-all (Join-Path $res 'font_cfgs') -o (Join-Path $res 'out\font')
if ($LASTEXITCODE -ne 0) { throw "font2c 失败 (exit $LASTEXITCODE)" }

# ---- 4. 图片取模（散 bin 输出到 build/pack） ----
Write-Host '==== img2bin_pack ===='
& $pack --config (Join-Path $res 'img2bin_pack.json') --folders $IMG_FOLDERS --emit bin
if ($LASTEXITCODE -ne 0) { throw "img2bin_pack 失败 (exit $LASTEXITCODE)" }

# ---- 5. 归一化：文件名元数据 → [补 6 字节 v2 头] → 角色短名 ----
# v2 头契约（Core/image_res.h）：[00][压缩<<4|像素][宽H][宽L][高H][高L]，宽高恒大端
Write-Host '==== normalize ===='
$fmtNibble = @{ rgb565 = 0x0; rgb888 = 0x1; rgb332 = 0x4; argb8888 = 0x5;
                argb6666 = 0x6; argb4444 = 0x7; argb8565 = 0x8; argb2222 = 0x9; ragb5155 = 0xA }
$algNibble = @{ raw = 0x0; rle = 0x1; imprle = 0x2; qoi = 0x3; indexqoi = 0x4; qoif = 0x5 }

Get-ChildItem (Join-Path $res 'build\pack') -Filter *.bin | ForEach-Object {
    if ($_.BaseName -notmatch '^(?<name>.+)_(?<fmt>[a-z0-9]+)_(?<alg>[a-z]+)_(?<end>be|le)_(?<w>\d+)x(?<h>\d+)$') {
        throw "无法解析文件名元数据: $($_.Name)"
    }
    $name = $Matches['name']
    $fmt  = $Matches['fmt']
    $alg  = $Matches['alg']
    $w    = [int]$Matches['w']
    $h    = [int]$Matches['h']
    if (-not $fmtNibble.ContainsKey($fmt)) { throw "未知像素格式: $fmt ($($_.Name))" }
    if (-not $algNibble.ContainsKey($alg)) { throw "未知压缩算法: $alg ($($_.Name))" }

    $payload = [System.IO.File]::ReadAllBytes($_.FullName)
    if (-not $IMG2BIN_HAS_HEADER) {
        $hdr = [byte[]]@(
            0x00,
            (($algNibble[$alg] -shl 4) -bor $fmtNibble[$fmt]),
            (($w -shr 8) -band 0xFF), ($w -band 0xFF),
            (($h -shr 8) -band 0xFF), ($h -band 0xFF))
        $payload = [byte[]]($hdr + $payload)
    }
    [System.IO.File]::WriteAllBytes((Join-Path $res "build\img\$name.bin"), $payload)
    Write-Host ("  {0,-16} {1}x{2}  {3}/{4}  {5:N0} B" -f "$name.bin", $w, $h, $fmt, $alg, $payload.Length)
}

# ---- 6. 生成内部图片数组 out/res_images.c/.h（确定性输出，无时间戳） ----
Write-Host '==== res_images codegen ===='
$sbH = New-Object System.Text.StringBuilder
$sbC = New-Object System.Text.StringBuilder
[void]$sbH.AppendLine('/* This file was generated by tool/res/update_resources.ps1. Do not edit. */')
[void]$sbH.AppendLine('#ifndef RES_IMAGES_H')
[void]$sbH.AppendLine('#define RES_IMAGES_H')
[void]$sbH.AppendLine('')
[void]$sbH.AppendLine('/* 内部 flash 图片数组，含 6 字节 v2 信息头（契约见 Core/image_res.h） */')
[void]$sbC.AppendLine('/* This file was generated by tool/res/update_resources.ps1. Do not edit. */')
[void]$sbC.AppendLine('#include "res_images.h"')
[void]$sbC.AppendLine('')
foreach ($name in $INTERNAL_IMAGES) {
    $binPath = Join-Path $res "build\img\$name.bin"
    if (-not (Test-Path $binPath)) { throw "内部图片缺失: $name（检查 input 文件夹与 INTERNAL_IMAGES 清单）" }
    $bytes = [System.IO.File]::ReadAllBytes($binPath)
    [void]$sbH.AppendLine("extern const unsigned char $name[$($bytes.Length)];")
    [void]$sbC.AppendLine("const unsigned char $name[$($bytes.Length)] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 12) {
        $chunk = $bytes[$i..([Math]::Min($i + 11, $bytes.Length - 1))]
        $line = '    ' + (($chunk | ForEach-Object { '0x{0:X2},' -f $_ }) -join ' ')
        [void]$sbC.AppendLine($line)
    }
    [void]$sbC.AppendLine('};')
    [void]$sbC.AppendLine('')
    Write-Host ("  {0,-16} {1:N0} B" -f $name, $bytes.Length)
}
[void]$sbH.AppendLine('')
[void]$sbH.AppendLine('#endif')
$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $res 'out\res_images.h'), $sbH.ToString(), $utf8)
[System.IO.File]::WriteAllText((Join-Path $res 'out\res_images.c'), $sbC.ToString(), $utf8)

# ---- 7. bin2c 合并（图片块在前、字库块在后，各块内按文件名排序） ----
Write-Host '==== bin2c ===='
& $bin2c --input (Join-Path $res 'build\img') --input (Join-Path $res 'out\font') `
         --output-path (Join-Path $res 'out') --output-name merged_bin
if ($LASTEXITCODE -ne 0) { throw "bin2c 失败 (exit $LASTEXITCODE)" }

# ---- 8. 汇总 ----
$mb = Get-Item (Join-Path $res 'out\merged_bin.bin')
Write-Host ''
Write-Host ('==== 完成 ====  merged_bin.bin = {0:N0} B ({1:N2} MB)' -f $mb.Length, ($mb.Length / 1MB))
