/* This file was generated by bin2c. */
#ifndef RES_IMG_H
#define RES_IMG_H

extern const unsigned char demo_argb8565_indexqoi_be_80x80[3244];

extern const unsigned char demo_argb8565_raw_be_80x80[19206];

extern const unsigned char demo_mapin_a8_indexqoimask_be_48x48[916];

extern const unsigned char demo_picture_a8_indexqoimask_be_48x48[767];

extern const unsigned char demo_powerdrill_a8_indexqoimask_be_48x48[482];

extern const unsigned char demo_powerdrill_a8_raw_be_48x48[2310];

extern const unsigned char demo_rgb565_indexqoi_be_128x64[6805];

extern const unsigned char demo_rgb565_raw_be_64x80[10246];

extern const unsigned char demo_windows_a8_indexqoimask_be_48x48[609];

extern const unsigned char demo_windows_a8_raw_be_48x48[2310];

#endif
